### PR TITLE
Fix correct class name in ModeratedModel example

### PR DESCRIPTION
**Pull request by krnr**

### CODE REVIEW

**Comment by dominno** [comment]
@krnr This is also wrong, it need to be GenericModerator class if you want to use it this way.

If you want to use ModeratedModel class then you have to use it on a Model class:

```
from django.db import models
from moderation.db import ModeratedModel


class MyModel(ModeratedModel):
    my_field = models.TextField()

    class Moderator:
        notify_user = False
```

**Comment by krnr** [comment]
@dominno there's nothing about it in the example. just `from moderation.db import ModeratedModel` and usage `AnotherModelModerator(ModelModerator)`, but what is `ModelModerator` in this case?

all this is very confusing

**Comment by dominno** [comment]
Example in docs is wrong 

It should be 

AnotherModelModerator(GenericModerator)

instead of:

AnotherModelModerator(ModelModerator)

**Comment by krnr** [comment]
Ah! finally! that's why I got the error mentioned in #158
thanks for clarifying

**Pull request closed without merging**
