### PR TITLE
Drop support Python2, Django<1.11. Add support Django 2.1, 2.2

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
This PR provides support only for Python 3.5+ and Django>=1.11

@dominno , PR is ready for review.
Also, we need to rewrite docs because it is outdated with this PR.

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Friendly ping @dominno

**Comment by dominno** [comment]
@DmytroLitvinov Thank you for your work. I have reviewed and have no question, can marge. Can you just update docs for info that changed ? Then will merge and push to pypi

**Comment by DmytroLitvinov** [comment]
Yes, of course.
I will adapt docs and ping you back.

**Comment by dominno** [comment]
also please update version in setup.py to '0.7.0'

**Comment by DmytroLitvinov** [comment]
Hi @dominno .
PR was refactor.
Please check latest commits: [this one](https://github.com/dominno/django-moderation/pull/178/commits/0135e5e650b20c99fc0bc85c8b852c08003ffe36) and [this](https://github.com/dominno/django-moderation/pull/178/commits/d8e819a4872bd94489e6cf37f1607c882c4cbad2)

**Pull request merged**
