### PR TITLE
Rename model fields to be shorter

### PR DESCRIPTION
**Pull request by blag**
I renamed a bunch of `ModeratedObject` model fields to make them less redundant and shorter.

Old Name | New Name | Change Reason | New Usage
-------- | -------- | ------------- | ---------
`date_created` | `created` | date is implied in the field type | `moderated_object.created`
`date_updated` | `updated` | date is implied in the field type | `moderated_object.updated`
`moderation_state` | `state` | removed redundancy | `moderated_object.state`
`moderation_status` | `status` | removed redundancy | `moderated_object.status`
`moderation_date` | `on` | removed redundancy | `moderated_object.on`
`moderation_reason` | `reason` | removed redundancy | `moderated_object.reason`
`moderated_by` | `by` | removed redundancy | `moderated_object.by`

I split this out from #148 because this is likely going to need more discussion.

### CODE REVIEW

**Comment by dominno** [comment]
@blag Tests are failing

**Comment by blag** [comment]
Yep, I've been working on that. Would you merge it once I fix the tests?

**Comment by dominno** [comment]
Yes, I will merge it when tests will be fixed.

**Comment by blag** [comment]
Rebased on top of #148, tests are now passing!

**Comment by dominno** [comment]
@blag I merged Your first PR, please rebase this one with current master and will I will merge it also. Thank you for hard work.

**Comment by blag** [comment]
I should also say that this PR forces users to drop South migrations in favor of Django's native migrations, because I don't create a South migration for 0003. Since the earliest supported release of Django (1.7) includes Django migrations, so I don't see this as a problem. Users who have previously used South will need to:

1. Configure South to use the correct `migrations-pre17` directory:

    ```python
    SOUTH_MIGRATION_MODULES = {
        'moderation': 'moderation.migrations-pre17',
    }
    ```

2. Use South to migrate up to 0002 in the migrations-pre17 directory:

    ```bash
    python manage.py migrate moderation 0001  # Skip this if already applied
    python manage.py migrate moderation 0002  # Skip this if already applied
    ```

3. Fake the first two Django migrations:

    ```bash
    python manage.py migrate 0001 --fake
    python manage.py migrate 0002 --fake
    ```

    If either of these error out with indications that tables or fields already exist, they can be skipped.

4. And finally use Django to migrate `0003`

    ```bash
    python manage.py migrate 0003
    ```

5. And finally remove the setting for South:

    ```python
    SOUTH_MIGRATION_MODULES = {
        # 'moderation': 'moderation.migrations-pre17',
    }
    ```

@dominno: Done, this is should be a one-click merge now.

Thanks for your responsiveness. Would you mind pushing two releases to PyPI? One now, and one more once I add Django 1.10 support?

**Comment by dominno** [comment]
@blag something is broken after this merge, can you check https://travis-ci.org/dominno/django-moderation/builds/155139922

**Comment by blag** [comment]
The brokeness you are seeing is limited to a single Django/Python combination, and it looks like it was a temporary PyPI outage of some sort (I've seen this happen with other projects).

Here's the relevant test output from the [Python 3.4/Django 1.9.9 test](https://travis-ci.org/dominno/django-moderation/jobs/155139930) (which passes):

>     Searching for webtest<2.1,>=2.0
>     Reading https://pypi.python.org/simple/webtest/
>     Best match: WebTest 2.0.23
>     Downloading https://pypi.python.org/packages/e7/d8/23d3f73976fb9ccba29f04565d1ddbd0300cf9c09db57e252718700d1203/WebTest-2.0.23.tar.gz#md5=b824dd81ba9fd50e138c5017e22eb3c7
>     Processing WebTest-2.0.23.tar.gz
>     <testing continues>

and here's the relevant output from the [Python 3.5/Django 1.8.14 test](https://travis-ci.org/dominno/django-moderation/jobs/155139931) (which fails):

>     Searching for webtest<2.1,>=2.0
>     Reading https://pypi.python.org/simple/webtest/
>     Download error on https://pypi.python.org/simple/webtest/: [Errno 104] Connection reset by peer -- Some packages may not be found!
>     Couldn't find index page for 'webtest' (maybe misspelled?)
>     Scanning index of all packages (this may take a while)
>     Reading https://pypi.python.org/simple/
>     No local packages or download links found for webtest<2.1,>=2.0
>     Coverage.py warning: No data was collected.
>     error: Could not find suitable distribution for Requirement.parse('webtest<2.1,>=2.0')
>     
>     
>     The command "coverage run setup.py test" exited with 1.
>     
>     Done. Your build exited with 1.

I don't see anything in there that indicates a problem with the code, and I've run all of the tests with tox (which I think is what Travis does) and the Python 3.5/Django 1.8.14 combination passes just fine.

Do you mind [kicking the tests off again manually](http://stackoverflow.com/a/17624403/6461688)? I'm curious to see if it happens again or if it was a transient occurrence.

**Comment by dominno** [comment]
@blag 

You were right. Can you write me summary for new release what was changed since last version that is on pypi, and include there that info that you wrote about migrations. Thank you

**Comment by blag** [comment]
@dominno Done: #150.

**Pull request merged**
