### PR TITLE
A bunch of fixups everywhere

### PR DESCRIPTION
**Pull request by blag**
I merged commits from other people and made a bunch of improvements to get `moderation` working with Django 1.9.

I had the tests skip over support for Django 1.10 because this package uses a lot of private functionality in Django, I couldn't get the tests to pass with 1.10 without breaking the tests for <1.10, and I've already spent way too much time on this as it is. So Django 1.10 support will need to go in a different PR. I will try to get back to that once I have cleared a lot of other stuff in my backlog, but I can't promise anything.

Commits I ~~stole~~ incorporated from other people
----------------------------------------------

* [Use `importlib` instead of Django's backported version (which has since been deprecated and removed)](https://github.com/dominno/django-moderation/commit/fcc8ad8da3b06be9820e961e5fb3b312df4e6c30)
* [Allow changes to fields that are excluded from moderation even if there are changes stacked up for the model](https://github.com/dominno/django-moderation/commit/e3e55fadadeb76ce123e465c99b436cc6036008e)

Making stuff work (and work better with) Django
-----------------------------------------------

* Instead of putting `auto_discover` in `<project>/urls.py`, move it into `moderation/apps.py` so it imports models once all apps are loaded, so moderation works with Django >= 1.9, and run it if the `MODERATION_AUTODISCOVER` setting is set to `True`
* The `auto_discover` function now does not try to import `moderation/moderators.py` because that was silently erroring out anyway
* I reordered imports and made them explicit and relative, as Django and PEP8 suggest
* Restricted tests to Django >=  1.7 and their supported Python versions

New Features
------------

* Allow the admin to resolve foreignkeys on a per-model basis by adding it to moderator options
* Added a `moderation_status` shortcut to models during registration
* Added `approve()` and `reject()` methods to our (new) custom queryset so we can approve and reject multiple `ModeratedObject`s at the same time (eg: in the admin changelist)
* Created a `EmailMultipleMessageBackend` using Django's `send_mass_mail` to send email to multiple people in a single email connection and use it when approving or rejecting using a queryset

Other Highlights
----------------

* Use [`Choices` from django-model-utils](https://github.com/dominno/django-moderation/commit/32f33ae7be9ea7457e6f89b028355a127e8a45e5) for choice fields (we can still use `SmallIntegerField`s as the database field
* Rename the `DJANGO_MODERATION_MODERATORS` setting to `MODERATION_MODERATORS` because the `DJANGO_` part of it is redundant. If users still set it now it will still work but it will emit a warning and text informing the user how to fix it.

Boring Stuff
------------

* Moved constants into their own file (`moderation/constants.py`) so they can be imported without importing `moderation/models.py` so we can use them before the app is fully loaded
* Formatted template better
* PEP8 formatting fixups
* Documentation fixups
* Typo fixes

### CODE REVIEW

**Comment by blag** [comment]
Also, note that I fixed the logic I pointed out in #87 in [this comment](https://github.com/dominno/django-moderation/pull/87#discussion-diff-72215531).

**Comment by blag** [comment]
Tests are now passing for Django 1.8 and 1.9, but I haven't quite figured it out for 1.7 and 1.10. I'll get back to this in a few days.

@dominno: Besides the test failures - how does this PR look? It's lots of changes but the changes in each commit should be fairly straightforward to review.

**Comment by dominno** [comment]
Hi, I'm on vacation now.  Will take a look at it after 14.08

Send from iPhone

Dnia 5 sie 2016 o godz. 15:47 blag <notifications@github.com> napisał(a):

**Comment by blag** [comment]
No worries, thanks!

**Comment by dominno** [comment]
Thank you @blag for the hard work you made on this PR. Code looks great. Just you need to fix tests for django 1.10. Please let me know when you fix them and then can merge the PR.

**Comment by blag** [comment]
To get all of the tests passing, I removed support for Django 1.10. I'll put that in a different PR once I get back to it, but I've already spent too much time working on this as it is. I'll put the Django 1.10 fixes I have so far in a separate branch and make a PR with that.

As it stands right now, the tests pass with Django 1.7-1.9 and all of their supported Python versions, and I'm declaring this PR done!

Please merge. 😄

**Pull request merged**
