### PR TITLE
Add support of django v.2.1

### PR DESCRIPTION
**Pull request by DmytroLitvinov**

### CODE REVIEW

**Comment by dominno** [comment]
@DmytroLitvinov thank you for PR. I cant merge unless tests are passing. Please check tests and update them. Thank you

**Comment by DmytroLitvinov** [comment]
Hi @dominno.
Can we drop support of django<1.11 and support only django>=1.11,<=2.2?

**Comment by dominno** [comment]
@DmytroLitvinov ok we can I think

**Comment by DmytroLitvinov** [comment]
Closed in favour of #178 .

**Pull request closed without merging**
