### PR TITLE
Update for Django 3.0

### PR DESCRIPTION
**Pull request by girardinsamuel**
I opened this PR to add compatibility with Django 3.

I did not ran tests yet, but for now I am using this version in a django 3 project and it seems to work.

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi,
I think it should be not strict at `setup.py` and better to write it just `>=1.11`.

**Comment by girardinsamuel** [comment]
Yes that's right I will fix this !

**Comment by grucha** [comment]
> I opened this PR to add compatibility with Django 3.
> 
> I did not ran tests yet, but for now I am using this version in a django 3 project and it seems to work.

@girardinsamuel how do you mean it seems to work? I see an ImportError:  

```
File "my-virtualenv/lib/python3.8/site-packages/moderation/db.py", line 16, in <module>
    from django.utils.six import with_metaclass
```

and it is directly related to Django 3.0 changes that drop support for py2 compatibility APIs:

https://docs.djangoproject.com/en/3.2/releases/3.0/#removed-private-python-2-compatibility-apis

**Comment by shawnngtq** [comment]
Commenting here to follow update. I would very much like to see it work for Django 3.x and perhaps even work with Python 3.9 😁

**Comment by dominno** [comment]
please rebase

**Comment by DmytroLitvinov** [comment]
Outdated since `master` already support Django@3

**Pull request closed without merging**
