### PR TITLE
Django 1.10+ support

### PR DESCRIPTION
**Pull request by blag**
This PR isn't ready yet, I'm just creating it to track progress on updating django-moderation to support Django 1.10+.

### CODE REVIEW

**Comment by dominno** [comment]
@blag ok thank you. I pushed ver 0.4.0 to pypi https://pypi.python.org/pypi/django-moderation/0.4.0

**Comment by pombredanne** [comment]
@blag any update? Adding this would be a++

**Comment by blag** [comment]
@pombredanne I think I got it working for me locally, but it doesn't pass tests. I'll try to focus on it later this week.

**Comment by blag** [comment]
I've worked on it, but I'm not happy with any of my code.

I cannot seem to get my code to pass tests on both Django 1.7 and 1.10, even when I separate them completely. At this point I don't really have any more time to commit to this. If somebody else can pick this up I will try to help them as best I can.

**Comment by bahoo** [comment]
Just coming onto this, but I'd throw out there: [Django dropped support for 1.7 in April 2015](https://www.djangoproject.com/download/#supported-versions), now two years back. 1.8 is a Long Term Support (LTS) release, so I'd throw a vote behind dropping 1.7 support and focusing on 1.8. Not my call of course, I'm new here :D but, for those interested in expeditious support of 1.10, at the expense of 1.7, you can follow along here: https://github.com/Our-Revolution/django-moderation

**Comment by blag** [comment]
@bahoo Does your branch just update the testing infrastructure to remove Django 1.7 and add Django 1.10 or does it actually make the necessary changes to make it run properly on Django 1.10?

Also, now that Django 1.11 is out we should probably add support for that.

**Comment by bahoo** [comment]
I didn't make any real changes to the underlying codebase, no. I'm relying on the tests, but they all passed, and I've been running it in my development environment without any issues.

I ran the tests on Django 1.11 too, which all passed, but thought it might be best to start with small steps. :)

What would be a good next step here? We're planning on using this in production on 1.10 in the near future, so I can lend a hand.

**Comment by blag** [comment]
@bahoo I think the next step is to submit a PR with your changes and get them merged into @dominno's repo. 😄

**Comment by blag** [comment]
Superseded by #154; closing.

**Comment by dominno** [comment]
@bahoo Thank you for your work. There is still some problem with tests, I see that they are failing.

**Comment by miigotu** [comment]
Any progress on this? Anxiously awaiting this, otherwise I have to write my own moderation-like feature for work =P

I tried to complete this PR and fix the tests myself, but the problems that remain are quite complicated to fix it seems.

**Comment by blag** [comment]
@miigotu I have no update, but I think it would be easier to update this PR than whip up something from scratch yourself... 😜

**Comment by bahoo** [comment]
I don't have much progress to report yet, unfortunately, @miigotu. My branch needs work but I think I underestimated the work involved. It's not something I'm actively working on as of now. (Wish I had better news, but just want to manage expectations!)

**Comment by miigotu** [comment]
Yeah, no problem. I'm writing something custom that serves this purpose in the project at work, and I'm hoping it can be broken out to release open source.  If I get something usable that I can release I'll ping you guys here if you are interested.

**Comment by blag** [comment]
Superseded with #155.

**Comment by blag** [comment]
I could use some help with #155, if anybody has time. Loading the JSON fixtures is failing on Django 1.10+ and I can't figure out why. Any help would be greatly appreciated.

**Comment by blag** [comment]
All (especially @miigotu): I finally got all of the tests to pass with Django 1.10 & 1.11, and Python 3.6. Please check out #155 for more!

**Pull request closed without merging**
